server/1/honey/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
     
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'honey.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^monitor/', include('monitor.urls', namespace='monitor')),
)

server/1/monitor/urls.py
from django.conf.urls import patterns, url
from monitor import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^prev/(?P<id>\d+)$', views.prev, name='prev'),
    url(r'^recive_gps/$', views.recive_gps, name='recive_gps'),
    url(r'^recive_file/$', views.recive_file, name='recive_file'),
    url(r'^demo/$', views.demo, name='demo'),
)

server/1/monitor/models.py
# -*- coding: utf-8 -*-

from django.db import models
import time, datetime


class Message(models.Model):

    type = models.IntegerField(default=0)  # 1前摄像头图  2后摄像头图  3声音  4 PGS信息
    file_path = models.CharField(max_length=4000)
    log_time = models.BigIntegerField(default=0)

    latitude = models.FloatField(default=0)  # 维度
    longitude = models.FloatField(default=0)  # 经度
    altitude = models.FloatField(default=0)  # 海拔高度
    address = models.CharField(default='',max_length=1000)  # 地址
    name = models.CharField(default='',max_length=200)  # 名称

    def __str__(self):
        return "目标正在经度 %s, 纬度 %s, 海拔 %s 米处活动。" % (self.longitude, self.latitude, self.altitude)

server/1/honey/views.py
from django.shortcuts import render
from django.http import HttpResponse
import django
import os
import sys


def home(request):
    return HttpResponse("Hello, honey! django: " + str(django.VERSION))

server/1/monitor/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from monitor.models import Message
from honey.settings import IS_SEA_ENV, UPLOAD_PATH, BASE_DIR
import json, os, uuid, time


def index(request):
    latest_message_list = Message.objects.order_by('-log_time')[:5]
    for item in latest_message_list:
        item.time_str = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(item.log_time))

    min_id = 0
    if latest_message_list:
        min_id = min(latest_message_list, key=lambda a: a.id).id
    context = {'latest_message_list': latest_message_list, 'min_id': min_id}
    return render(request, 'monitor/index.html', context)


def prev(request, id):
    latest_message_list = Message.objects.filter(id__lt=id).order_by('-log_time')[:5]
    for item in latest_message_list:
        item.time_str = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(item.log_time))
    min_id = 0
    if latest_message_list:
        min_id = min(latest_message_list, key=lambda a: a.id).id
    context = {'latest_message_list': latest_message_list, 'min_id':min_id }
    return render(request, 'monitor/prev.html', context)


def recive_gps(request):

    json = request.POST['data']
    data = json.loads(json);

    for item in data:
        msg = Message(type=4,
                  log_time=item['log_time'],
                  latitude=item['latitude'],
                  longitude=item['longitude'],
                  altitude=item['altitude'],
                  address=item['address'],
                  name=item['name']),

        msg.save()

    return HttpResponse("Hello, world. You're at the monitor recive_gps.")


def recive_file(request):

    type = request.POST['type']
    log_time = request.POST['log_time']
    latitude = request.POST['latitude']
    longitude = request.POST['longitude']
    altitude = request.POST['altitude']
    address = request.POST['address']
    name = request.POST['name']
    file_url = ''
    if not request.FILES:
        type = 4
    else:
        file_obj = request.FILES['file']
        filename = str(uuid.uuid1()) + file_obj.name
        if IS_SEA_ENV:
            from sae.storage import Bucket
            bucket = Bucket('res')
            bucket.put_object(filename, file_obj.read())
            file_url = bucket.generate_url(filename)
        else:
            file_path = os.path.join(BASE_DIR, UPLOAD_PATH)
            if not os.path.exists(file_path):
                os.makedirs(file_path)
            file_path = os.path.join(file_path,filename)
            dest = open(file_path,'wb+')
            dest.write(file_obj.read())
            dest.close()
            file_url = os.path.join("/", UPLOAD_PATH.replace("\\", "/"), filename)

    msg = Message(type=type,
                  file_path=file_url,
                  log_time=log_time,
                  latitude=latitude,
                  longitude=longitude,
                  altitude=altitude,
                  address=address,
                  name=name)
    msg.save()

    return HttpResponse("Hello, world. You're at the monitor recive_file.")


def demo(request):
    return render(request, 'monitor/demo.html')

server/1/monitor/templates/monitor/demo.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>UPLOAD GPS INFO DEMO</h1>
<form action="/monitor/recive_file/" enctype="multipart/form-data" method="POST">
    <table>
        <tr>
            <td>type</td>
            <td><input type="text" name="type"></td>
        </tr>
        <tr>
            <td>log_time</td>
            <td><input type="text" name="log_time"></td>
        </tr>
        <tr>
            <td>latitude</td>
            <td><input type="text" name="latitude"></td>
        </tr>
        <tr>
            <td>longitude</td>
            <td><input type="text" name="longitude"></td>
        </tr>
        <tr>
            <td>altitude</td>
            <td><input type="text" name="altitude"></td>
        </tr>
        <tr>
            <td>address</td>
            <td><input type="text" name="address"></td>
        </tr>
        <tr>
            <td>name</td>
            <td><input type="text" name="name"></td>
        </tr>
        <tr>
            <td>file</td>
            <td><input type="file" name="file"></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="上传"></td>
        </tr>
    </table>
</form>
</body>
</html>

server/1/monitor/templates/monitor/index.html
<!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Index</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>
    <h1>Index</h1>
    <div class="container-fluid">
        <div class="list-group">
            {% if latest_message_list %}
                {% for item in latest_message_list %}
                <a href="#" class="list-group-item text-center">
                    <h4 class="list-group-item-heading text-center">{{ item.time_str }}</h4>
                    <p class="list-group-item-text">
                        {{ item }}
                        <div><img src="http://apis.map.qq.com/ws/staticmap/v2/?center={{ item.latitude }},{{ item.longitude }}&markers=color:blue|label:A|{{ item.latitude }},{{ item.longitude }}&zoom=15&size=260x300&maptype=hybrid&key=OBNBZ-JRLWR-6DWWW-WQFYY-VZEOZ-ERF3S"></div>
                    </p>
                    {% if item.file_path %}
                    <p class="list-group-item-text">
                        {% if item.type == 1 or item.type == 2 %}
                        <img src="{{ item.file_path }}">
                        {% endif %}
                    </p>
                    {% endif %}
                </a>
                {% endfor %}
                <a href="#" class="list-group-item btn btn-primary more" name="{% url 'monitor:prev' min_id %}">查看更多>></a>
            {% else %}
            <a href="#" class="list-group-item text-center">暂无记录</a>
            {% endif %}
        </div>
    </div>
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(function(){
            $(".more").on("click", function(){
                var $this = $(this);
                if($this.hasClass("disabled")){
                    return false;
                }

                $this.addClass("disabled").html("正在获取...");
                $.get($this.attr("name"), function(data){
                    $this.before(data);
                    $this.remove();
                })

                return false;
            });
        })
    </script>
</body>
</html>

server/1/monitor/templates/monitor/prev.html
{% if latest_message_list %}
    {% for item in latest_message_list %}
    <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">{{ item.time_str }}</h4>
        <p class="list-group-item-text">
            {{ item }}
            <div><img src="http://apis.map.qq.com/ws/staticmap/v2/?center={{ item.latitude }},{{ item.longitude }}&markers=color:blue|label:A|{{ item.latitude }},{{ item.longitude }}&zoom=15&size=260x300&maptype=hybrid&key=OBNBZ-JRLWR-6DWWW-WQFYY-VZEOZ-ERF3S"></div>
        </p>

        {% if item.file_path %}
        <p class="list-group-item-text">
            {% if item.type == 1 or item.type == 2 %}
            <img src="{{ item.file_path }}">
            {% endif %}
        </p>
        {% endif %}
    </a>
    {% endfor %}
    <a href="#" class="list-group-item btn btn-primary more" name="{% url 'monitor:prev' min_id %}">查看更多>></a>
{% else %}
<a href="#" class="list-group-item text-center">没了，就这么些了。</a>
{% endif %}